alter table public.submissions
  add column if not exists estimated_image_cost_cents numeric(10, 4) not null default 0,
  add column if not exists image_provider text,
  add column if not exists image_model text;

alter table public.games
  add column if not exists estimated_image_cost_cents numeric(10, 4) not null default 0;

create index if not exists submissions_game_cost_idx
  on public.submissions (game_id, estimated_image_cost_cents);

create table if not exists public.image_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  room_code text not null,
  game_id bigint not null,
  submission_id bigint not null,
  reporter_name text not null,
  reported_player_name text not null,
  status text not null default 'open' check (status in ('open', 'reviewed', 'dismissed', 'removed')),
  game_mode text,
  image_style text,
  prompt_source text,
  round_prompt text,
  submission_text text
);

create unique index if not exists image_reports_submission_reporter_unique
  on public.image_reports (submission_id, reporter_name);

create index if not exists image_reports_room_status_idx
  on public.image_reports (room_code, status);

create index if not exists image_reports_game_id_idx
  on public.image_reports (game_id);

create or replace view public.game_cost_summary as
select
  games.id as game_id,
  games.room_code,
  games.created_at,
  games.game_mode,
  games.image_style,
  games.estimated_image_cost_cents as game_estimated_image_cost_cents,
  count(submissions.id) filter (where submissions.image_url is not null) as generated_image_count,
  coalesce(sum(submissions.estimated_image_cost_cents), 0) as submission_estimated_image_cost_cents
from public.games
left join public.submissions on submissions.game_id = games.id
group by
  games.id,
  games.room_code,
  games.created_at,
  games.game_mode,
  games.image_style,
  games.estimated_image_cost_cents;
