create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  room_code text,
  game_id bigint,
  player_id bigint,
  player_name text,
  stage text,
  metadata jsonb not null default '{}'::jsonb,
  country text,
  region text,
  city text,
  timezone text,
  user_agent text,
  referrer text
);

create index if not exists game_events_created_at_idx
  on public.game_events (created_at desc);

create index if not exists game_events_event_name_idx
  on public.game_events (event_name, created_at desc);

create index if not exists game_events_room_idx
  on public.game_events (room_code, created_at desc);

create index if not exists game_events_game_idx
  on public.game_events (game_id, created_at desc);

create index if not exists game_events_country_idx
  on public.game_events (country, created_at desc);

alter table public.game_events enable row level security;

drop policy if exists "Service can manage game events" on public.game_events;
create policy "Service can manage game events"
on public.game_events
for all
to service_role
using (true)
with check (true);
