create table if not exists public.image_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  room_code text not null,
  game_id bigint not null,
  submission_id bigint not null,
  rater_name text not null,
  submission_player_name text not null,
  rating text not null check (rating in ('funny', 'meh', 'bad')),
  image_provider text,
  image_model text,
  image_style text,
  game_mode text,
  prompt_source text
);

create unique index if not exists image_feedback_submission_rater_unique
  on public.image_feedback (submission_id, rater_name);

create index if not exists image_feedback_room_code_idx
  on public.image_feedback (room_code);

create index if not exists image_feedback_game_id_idx
  on public.image_feedback (game_id);
