from __future__ import annotations

import datetime
import sys
from pathlib import Path

import openpyxl


EXPECTED_HEADERS = [
    "id",
    "prompt",
    "category",
    "active",
    "personal",
    "image_style",
    "prompt_rating",
]

# public.prompts has a check constraint (prompts_prompt_rating_check) that
# only allows these values (or null). Anything else - e.g. a content-batch
# tag like "fast_scene_v2" left in the sheet by mistake - must be coerced to
# null rather than inserted as-is, or the reload script fails the constraint.
VALID_PROMPT_RATINGS = {"good", "ehhh", "bad"}


def sql_value(value: object, *, column: str | None = None) -> str:
    if column == "prompt_rating" and value is not None and value not in VALID_PROMPT_RATINGS:
        return "null"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(int(value)) if float(value).is_integer() else str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: generate_prompt_reload_sql.py <workbook.xlsx> <output.sql>")
        return 1

    workbook_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    workbook = openpyxl.load_workbook(workbook_path, read_only=True, data_only=True)
    worksheet = workbook["DB_Import"]

    headers = [cell.value for cell in next(worksheet.iter_rows(min_row=1, max_row=1))]
    if headers != EXPECTED_HEADERS:
        raise ValueError(f"Unexpected DB_Import headers: {headers}")

    rows: list[dict[str, object]] = []
    for cells in worksheet.iter_rows(min_row=2, values_only=True):
        if not any(value is not None for value in cells):
            continue
        row = dict(zip(headers, cells, strict=True))
        if row["id"] is None or not row["prompt"]:
            continue
        rows.append(row)

    ids = [row["id"] for row in rows]
    duplicate_ids = sorted({prompt_id for prompt_id in ids if ids.count(prompt_id) > 1})
    if duplicate_ids:
        raise ValueError(f"Duplicate prompt ids: {duplicate_ids[:10]}")

    lines: list[str] = [
        "-- Reload public.prompts from ai_party_game_500_more_v2.xlsx / DB_Import",
        "-- Run this in Supabase SQL Editor. It replaces the current Classic prompt deck.",
        f"-- Generated by Codex on {datetime.date.today().isoformat()}",
        "",
        "begin;",
        "",
        "-- Remove the existing classic prompts before loading the new deck.",
        "delete from public.prompts;",
        "",
        "insert into public.prompts (id, prompt, category, active, personal, image_style, prompt_rating)",
        "values",
    ]

    for index, row in enumerate(rows):
        suffix = "," if index < len(rows) - 1 else ";"
        values = ", ".join(sql_value(row[column], column=column) for column in EXPECTED_HEADERS)
        lines.append(f"  ({values}){suffix}")

    lines.extend(
        [
            "",
            "-- Keep the serial/identity counter ahead of the inserted IDs.",
            "select setval(pg_get_serial_sequence('public.prompts', 'id'), coalesce((select max(id) from public.prompts), 1), true);",
            "",
            "commit;",
            "",
            "-- Quick check: should return 500 prompts after the reload.",
            "select count(*) as prompt_count from public.prompts;",
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} prompts to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
